[2025-02-14 02:05:28,258] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:05:28,277] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:05:28,278] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:05:28,278] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-02-14 02:05:28,278] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:05:28,287] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2025-02-13T00:00:00+00:00
[2025-02-14 02:05:28,290] {standard_task_runner.py:52} INFO - Started process 3370 to run task
[2025-02-14 02:05:28,295] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_one', '2025-02-13T00:00:00+00:00', '--job-id', '101', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmppazo2ago', '--error-file', '/tmp/tmpvzj8yrku']
[2025-02-14 02:05:28,296] {standard_task_runner.py:77} INFO - Job 101: Subtask task_one
[2025-02-14 02:05:28,344] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [running]> on host 81ce9e7c2327
[2025-02-14 02:05:28,402] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2025-02-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-13T00:00:00+00:00
[2025-02-14 02:05:28,404] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 30, in catalog
    with open("00_urls.txt", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '00_urls.txt'
[2025-02-14 02:05:28,409] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Project, task_id=task_one, execution_date=20250213T000000, start_date=20250214T020528, end_date=20250214T020528
[2025-02-14 02:05:28,437] {local_task_job.py:151} INFO - Task exited with return code 1
[2025-02-14 02:22:28,514] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:22:28,526] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:22:28,527] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:22:28,527] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-02-14 02:22:28,528] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:22:28,543] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2025-02-13T00:00:00+00:00
[2025-02-14 02:22:28,552] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_one', '2025-02-13T00:00:00+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpvul3vu6c', '--error-file', '/tmp/tmpk726pgxo']
[2025-02-14 02:22:28,547] {standard_task_runner.py:52} INFO - Started process 436 to run task
[2025-02-14 02:22:28,553] {standard_task_runner.py:77} INFO - Job 112: Subtask task_one
[2025-02-14 02:22:28,617] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [running]> on host ad36e95eb2b4
[2025-02-14 02:22:28,680] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2025-02-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-13T00:00:00+00:00
[2025-02-14 02:22:28,682] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 30, in catalog
    with open("urls.txt", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'urls.txt'
[2025-02-14 02:22:28,687] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Project, task_id=task_one, execution_date=20250213T000000, start_date=20250214T022228, end_date=20250214T022228
[2025-02-14 02:22:28,735] {local_task_job.py:151} INFO - Task exited with return code 1
[2025-02-14 02:37:07,762] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:37:07,782] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 02:37:07,782] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:37:07,782] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-02-14 02:37:07,783] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 02:37:07,791] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2025-02-13T00:00:00+00:00
[2025-02-14 02:37:07,800] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_one', '2025-02-13T00:00:00+00:00', '--job-id', '121', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp934fc3_y', '--error-file', '/tmp/tmpyj7amz9p']
[2025-02-14 02:37:07,795] {standard_task_runner.py:52} INFO - Started process 542 to run task
[2025-02-14 02:37:07,801] {standard_task_runner.py:77} INFO - Job 121: Subtask task_one
[2025-02-14 02:37:07,849] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [running]> on host 86e52ee3d57a
[2025-02-14 02:37:07,908] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2025-02-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-13T00:00:00+00:00
[2025-02-14 02:37:07,910] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 30, in catalog
    with open("urls.txt", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'urls.txt'
[2025-02-14 02:37:07,913] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Project, task_id=task_one, execution_date=20250213T000000, start_date=20250214T023707, end_date=20250214T023707
[2025-02-14 02:37:07,941] {local_task_job.py:151} INFO - Task exited with return code 1
[2025-02-14 03:01:17,611] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 03:01:17,622] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14 03:01:17,623] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 03:01:17,623] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2025-02-14 03:01:17,623] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-02-14 03:01:17,639] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2025-02-13T00:00:00+00:00
[2025-02-14 03:01:17,648] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project', 'task_one', '2025-02-13T00:00:00+00:00', '--job-id', '126', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpr4x_e137', '--error-file', '/tmp/tmpu8ehbw0y']
[2025-02-14 03:01:17,643] {standard_task_runner.py:52} INFO - Started process 195 to run task
[2025-02-14 03:01:17,649] {standard_task_runner.py:77} INFO - Job 126: Subtask task_one
[2025-02-14 03:01:17,704] {logging_mixin.py:104} INFO - Running <TaskInstance: Project.task_one 2025-02-13T00:00:00+00:00 [running]> on host 9e3f73609008
[2025-02-14 03:01:17,766] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2025-02-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-13T00:00:00+00:00
[2025-02-14 03:01:18,629] {logging_mixin.py:104} INFO - wrote file: m1a.html
[2025-02-14 03:01:18,629] {logging_mixin.py:104} INFO - pulled: m1a.html
[2025-02-14 03:01:18,629] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:01:33,991] {logging_mixin.py:104} INFO - wrote file: m1b.html
[2025-02-14 03:01:33,992] {logging_mixin.py:104} INFO - pulled: m1b.html
[2025-02-14 03:01:33,992] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:01:49,497] {logging_mixin.py:104} INFO - wrote file: m1c.html
[2025-02-14 03:01:49,497] {logging_mixin.py:104} INFO - pulled: m1c.html
[2025-02-14 03:01:49,497] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:02:04,936] {logging_mixin.py:104} INFO - wrote file: m2a.html
[2025-02-14 03:02:04,937] {logging_mixin.py:104} INFO - pulled: m2a.html
[2025-02-14 03:02:04,937] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:02:20,378] {logging_mixin.py:104} INFO - wrote file: m2b.html
[2025-02-14 03:02:20,378] {logging_mixin.py:104} INFO - pulled: m2b.html
[2025-02-14 03:02:20,379] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:02:35,778] {logging_mixin.py:104} INFO - wrote file: m2c.html
[2025-02-14 03:02:35,779] {logging_mixin.py:104} INFO - pulled: m2c.html
[2025-02-14 03:02:35,779] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:02:51,216] {logging_mixin.py:104} INFO - wrote file: m3a.html
[2025-02-14 03:02:51,218] {logging_mixin.py:104} INFO - pulled: m3a.html
[2025-02-14 03:02:51,218] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:03:06,609] {logging_mixin.py:104} INFO - wrote file: m3b.html
[2025-02-14 03:03:06,610] {logging_mixin.py:104} INFO - pulled: m3b.html
[2025-02-14 03:03:06,611] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:03:21,972] {logging_mixin.py:104} INFO - wrote file: m4a.html
[2025-02-14 03:03:21,974] {logging_mixin.py:104} INFO - pulled: m4a.html
[2025-02-14 03:03:21,974] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:03:37,322] {logging_mixin.py:104} INFO - wrote file: m4b.html
[2025-02-14 03:03:37,322] {logging_mixin.py:104} INFO - pulled: m4b.html
[2025-02-14 03:03:37,323] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:03:52,757] {logging_mixin.py:104} INFO - wrote file: m4c.html
[2025-02-14 03:03:52,758] {logging_mixin.py:104} INFO - pulled: m4c.html
[2025-02-14 03:03:52,759] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:04:08,061] {logging_mixin.py:104} INFO - wrote file: m4d.html
[2025-02-14 03:04:08,062] {logging_mixin.py:104} INFO - pulled: m4d.html
[2025-02-14 03:04:08,062] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:04:23,386] {logging_mixin.py:104} INFO - wrote file: m4e.html
[2025-02-14 03:04:23,387] {logging_mixin.py:104} INFO - pulled: m4e.html
[2025-02-14 03:04:23,387] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:04:38,778] {logging_mixin.py:104} INFO - wrote file: m4f.html
[2025-02-14 03:04:38,779] {logging_mixin.py:104} INFO - pulled: m4f.html
[2025-02-14 03:04:38,780] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:04:53,988] {logging_mixin.py:104} INFO - wrote file: m4g.html
[2025-02-14 03:04:53,990] {logging_mixin.py:104} INFO - pulled: m4g.html
[2025-02-14 03:04:53,990] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:05:09,388] {logging_mixin.py:104} INFO - wrote file: m5a.html
[2025-02-14 03:05:09,389] {logging_mixin.py:104} INFO - pulled: m5a.html
[2025-02-14 03:05:09,390] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:05:24,774] {logging_mixin.py:104} INFO - wrote file: m5b.html
[2025-02-14 03:05:24,774] {logging_mixin.py:104} INFO - pulled: m5b.html
[2025-02-14 03:05:24,775] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:05:40,184] {logging_mixin.py:104} INFO - wrote file: m6a.html
[2025-02-14 03:05:40,184] {logging_mixin.py:104} INFO - pulled: m6a.html
[2025-02-14 03:05:40,185] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:05:55,593] {logging_mixin.py:104} INFO - wrote file: m6b.html
[2025-02-14 03:05:55,594] {logging_mixin.py:104} INFO - pulled: m6b.html
[2025-02-14 03:05:55,594] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:06:10,998] {logging_mixin.py:104} INFO - wrote file: m6c.html
[2025-02-14 03:06:10,999] {logging_mixin.py:104} INFO - pulled: m6c.html
[2025-02-14 03:06:10,999] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:06:26,560] {logging_mixin.py:104} INFO - wrote file: m7a.html
[2025-02-14 03:06:26,561] {logging_mixin.py:104} INFO - pulled: m7a.html
[2025-02-14 03:06:26,561] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:06:41,929] {logging_mixin.py:104} INFO - wrote file: m8a.html
[2025-02-14 03:06:41,930] {logging_mixin.py:104} INFO - pulled: m8a.html
[2025-02-14 03:06:41,930] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:06:57,323] {logging_mixin.py:104} INFO - wrote file: m8b.html
[2025-02-14 03:06:57,323] {logging_mixin.py:104} INFO - pulled: m8b.html
[2025-02-14 03:06:57,324] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:07:12,627] {logging_mixin.py:104} INFO - wrote file: m9a.html
[2025-02-14 03:07:12,627] {logging_mixin.py:104} INFO - pulled: m9a.html
[2025-02-14 03:07:12,628] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:07:28,016] {logging_mixin.py:104} INFO - wrote file: m9b.html
[2025-02-14 03:07:28,017] {logging_mixin.py:104} INFO - pulled: m9b.html
[2025-02-14 03:07:28,018] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:07:43,526] {logging_mixin.py:104} INFO - wrote file: m10a.html
[2025-02-14 03:07:43,526] {logging_mixin.py:104} INFO - pulled: m10a.html
[2025-02-14 03:07:43,526] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:07:58,917] {logging_mixin.py:104} INFO - wrote file: m10b.html
[2025-02-14 03:07:58,918] {logging_mixin.py:104} INFO - pulled: m10b.html
[2025-02-14 03:07:58,919] {logging_mixin.py:104} INFO - --- waiting ---
[2025-02-14 03:08:14,139] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 40, in catalog
    data = pull(url)
  File "/opt/airflow/dags/assignment.py", line 18, in pull
    response = urllib.request.urlopen(url).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2025-02-14 03:08:14,159] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Project, task_id=task_one, execution_date=20250213T000000, start_date=20250214T030117, end_date=20250214T030814
[2025-02-14 03:08:14,255] {local_task_job.py:151} INFO - Task exited with return code 1
